const $=s=>document.querySelector(s);let chapters=[],read=new Set(),allOpen=false;
function esc(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function inline(s){return esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>')}
function md(text){let a=text.split(/\r?\n/),o='',list=false,code=false;for(let x of a){if(x.startsWith('```')){code=!code;o+=code?'<pre class="md-code">':'</pre>';continue}if(code){o+=esc(x)+'\n';continue}if(/^---+$/.test(x.trim())){if(list){o+='</ul>';list=false}o+='<hr>';continue}let h=x.match(/^(#{2,6})\s+(.*)/);if(h){if(list){o+='</ul>';list=false}let n=h[1].length;let heading=h[2].match(/^(\d+(?:\.\d+)+)(\s+)(.*)$/);let headingHtml=heading?`<span class="section-number">${heading[1]}</span>${inline(heading[2]+heading[3])}`:inline(h[2]);o+=`<h${n+1}>${headingHtml}</h${n+1}>`;continue}if(/^\s*[-*] /.test(x)){if(!list){o+='<ul>';list=true}o+=`<li>${inline(x.replace(/^\s*[-*] /,''))}</li>`;continue}if(list){o+='</ul>';list=false}if(/^>/.test(x)){o+=`<blockquote>${inline(x.replace(/^>\s?/,''))}</blockquote>`;continue}if(/^\|/.test(x)){let c=x.split('|').slice(1,-1).map(v=>v.trim());if(c.every(v=>/^[-: ]+$/.test(v)))continue;o+='<div class="md-table-row">'+c.map(v=>`<span>${inline(v)}</span>`).join('')+'</div>';continue}if(x.trim())o+=`<p>${inline(x)}</p>`}if(list)o+='</ul>';return o}
function parse(text){return text.split(/^# /m).filter(x=>x.trim()).map((x,i)=>{let p=x.split(/\r?\n/),title=p.shift().trim();return {title,body:p.join('\n'),num:i}}).filter(c=>!/^Deutsch für Anfänger/.test(c.title))}
const groups=[{title:'基础问候与德语字母',de:'Begrüßung · Alphabet',icon:'👋',ids:[0,1]},{title:'W-Fragen、代词与 sein',de:'Fragen · Pronomen · Sein',icon:'❓',ids:[2,3,4,5]},{title:'自我介绍、动词变位与职业',de:'Vorstellen · Konjugation · Beruf',icon:'🪪',ids:[6,7,8]},{title:'数字、日期/时间、金钱与年龄',de:'Zahlen · Uhr · Geld · Alter',icon:'🔢',ids:[9,10,11,12]},{title:'教室词汇、名词性别与单复数',de:'Klassenzimmer · Genus',icon:'✏️',ids:[13,14,15,16]},{title:'食物、饮料与餐厅点餐',de:'Essen · Trinken · Restaurant',icon:'🥨',ids:[17,18,19,20]},{title:'德语基本句型、疑问句与 Akkusativ',de:'Satzbau · Fragen · Akkusativ',icon:'📝',ids:[21,22,23,24,25]},{title:'家庭与 Possessivpronomen',de:'Familie · Possessiv',icon:'👨‍👩‍👧',ids:[26,27,28,29,30,31]},{title:'兴趣爱好、否定冠词与 Akkusativ 代词',de:'Hobby · Kein · Pronomen',icon:'🎨',ids:[32,33,34,35,36,37]},{title:'衣服、形容词与颜色',de:'Kleidung · Adjektive · Farben',icon:'🧥',ids:[38,39,40,41,42]},{title:'动物与健康表达',de:'Tiere · Gesundheit',icon:'🐻',ids:[43,44,45]},{title:'考试复习',de:'Prüfung · Wiederholung',icon:'📚',ids:[46,47,48,49,50]}];
function groupFor(i){return groups.findIndex(g=>g.ids.includes(i))}
function renderNav(){let nav=$('#chapterNav');nav.innerHTML=groups.map((g,gi)=>`<button data-i="${g.ids[0]}" class="chapter-nav-item"><span class="num">${String(gi+1).padStart(2,'0')}</span><span><b>第${gi+1}章</b><small>${g.title}</small></span></button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>openChapter(+b.dataset.i));}
function alphabetCard(){const letters=[['A','ah'],['B','beh'],['C','tseh'],['D','deh'],['E','eh'],['F','eff'],['G','geh'],['H','hah'],['I','ee'],['J','yot'],['K','car'],['L','ell'],['M','emm'],['N','enn'],['O','oh'],['P','peh'],['Q','koo'],['R','air'],['S','ess'],['T','teh'],['U','oo'],['V','fow'],['W','veh'],['X','iks'],['Y','oopsilon'],['Z','tsett']];return `<article class="alphabet-card"><div class="alphabet-head"><span>🔤</span><div><b>基础字母表 · Das Alphabet</b><small>26 个一般字母的德语读法 · 罗马字母提示</small></div></div><div class="alphabet-grid">${letters.map(x=>`<div><strong>${x[0]}</strong><span>${x[1]}</span></div>`).join('')}</div><div class="special-letters"><b>特殊字符</b><span>Ä ä · Ö ö · Ü ü · ß（Eszett / scharfes S）</span></div><p>提示：字母读法用于拼写姓名，例如 <b>Ich buchstabiere T-H-O-M-A-S.</b> 变音符号和 ß 的详细规则见本章后面的笔记。</p></article>`}
function render(){let r=$('#reader');r.innerHTML=groups.map((g,gi)=>`<div class="chapter-divider" id="group-${gi}"><span>${g.icon}</span><div><b>第 ${gi+1} 章</b><strong>${g.title}</strong><small>${g.de} · ${g.ids.length} 个知识单元</small></div></div>${gi===0?alphabetCard():''}${g.ids.map((i,j)=>{let c=chapters[i];return `<article class="chapter ${i===0?'open':''}" id="chapter-${i}" data-i="${i}"><div class="chapter-head"><span class="chapter-num">${String(j+1).padStart(2,'0')}</span><div class="chapter-title"><h2>${inline(c.title)}</h2><small>第 ${gi+1} 章 · ${g.title}</small></div><span class="chapter-toggle">＋</span></div><div class="chapter-body">${md(c.body)}</div></article>`}).join('')}`).join('');r.querySelectorAll('.chapter-head').forEach(h=>h.onclick=()=>toggle(+h.parentElement.dataset.i));updateProgress();}
function sectionHint(i){let g=groupFor(i);return g>=0?`第 ${g+1} 章 · ${groups[g].title}`:''}
function toggle(i){let el=$(`#chapter-${i}`);el.classList.toggle('open');if(el.classList.contains('open')){read.add(i);localStorage.setItem('de-read-v2',JSON.stringify([...read]));renderNav();updateProgress()}}
function openChapter(i){let el=$(`#chapter-${i}`);el.classList.add('open');el.scrollIntoView({behavior:'smooth',block:'start'});read.add(i);localStorage.setItem('de-read-v2',JSON.stringify([...read]));renderNav();updateProgress()}
function updateProgress(){$('#readCount').textContent=`${read.size} / ${chapters.length}`;$('#readBar').style.width=(read.size/Math.max(chapters.length,1)*100)+'%'}
function search(){let panel=$('#searchPanel');panel.classList.toggle('hidden');if(!panel.classList.contains('hidden')){$('#searchInput').focus();$('#searchInput').oninput=filter}}
function filter(){let q=$('#searchInput').value.trim().toLowerCase(),count=0;document.querySelectorAll('.chapter').forEach((el,i)=>{let yes=!q||(`${chapters[i].title} ${chapters[i].body}`).toLowerCase().includes(q);el.style.display=yes?'':'none';if(yes&&q)count++});$('#searchMeta').textContent=q?`${count} 个章节匹配`:''}
async function init(){try{let text=await(await fetch('Notizen_Lernnotizen.md')).text();chapters=parse(text);read=new Set(JSON.parse(localStorage.getItem('de-read-v2')||'[]'));renderNav();render();$('#loading').remove();$('#continueBtn').onclick=()=>openChapter(Math.min(read.size,chapters.length-1));$('#allBtn').onclick=()=>{allOpen=!allOpen;document.querySelectorAll('.chapter').forEach(x=>x.classList.toggle('open',allOpen));$('#allBtn').textContent=allOpen?'全部收起':'全部展开'};$('#searchBtn').onclick=search;$('#themeBtn').onclick=()=>document.body.classList.toggle('dark');$('#menuBtn').onclick=()=>document.body.classList.toggle('sidebar-open')}catch(e){$('#loading p').textContent='笔记载入失败，请刷新页面重试。'}}init();